### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by skyforblue** [zerollzeng/tensorrt-zoo#10]
![image](https://user-images.githubusercontent.com/35251521/79178133-ff03e300-7e36-11ea-89a2-578414a2f224.png)

**Comment by zerollzeng** [comment]
Did you use the latest tiny-tensorrt?

**Comment by skyforblue** [comment]
我直接clone的

**Comment by skyforblue** [comment]
pybind 和 tiny-tensorrt 都是master分支的

**Comment by zerollzeng** [comment]
try re-clone the project with
```
git clone --recursive https://github.com/zerollzeng/tensorrt-zoo.git
```
or try reset the tiny-tensorrt commit to 69e64d1, becasue tensort-zoo is not compatible with latest tiny-tensorrt

BTW you should take a look at https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by skyforblue** [comment]
我试一下

**Comment by skyforblue** [comment]
Tanks,已经编译成功了，但在运行的时候出现错误，prototxt已经修改，但是出现了下面的错误
![image](https://user-images.githubusercontent.com/35251521/79180306-3628c300-7e3c-11ea-9c1c-4791395f27d5.png)

**Comment by zerollzeng** [comment]
take a look at
https://github.com/zerollzeng/tensorrt-zoo/blob/3bc4306972ce4d0b3e5936ad3b541be51e14ec07/openpose/testopenpose.cpp#L40

the docs of this project isn't well update, because I was mainly focus on the project tiny-tensorrt. please refer to the source code first

**Comment by zerollzeng** [comment]
Close due to inativity
