### ISSUE TITLE
No keypoints output with testopenpose

### ISSUE THREAD

**Issue by MolianWH** [zerollzeng/tensorrt-zoo#13]
Hi,
I run testopenpose, but "result.jpg"  doesn't show keypoints.

**Comment by zerollzeng** [comment]
did you solved it？ or post more information

**Comment by MolianWH** [comment]
sorry to reply late. It wasn't solved yet. Below is the output information
![Screenshot from 2020-04-20 18-23-38](https://user-images.githubusercontent.com/33748947/79741819-756f7c00-8334-11ea-8011-eb3aec128c8e.png)

**Comment by MolianWH** [comment]
When debug testopenpose to `openpose.DoInference(inputData, result);`  result size is zero. 
output information shows input and output null (see last comment picture)

**Comment by zerollzeng** [comment]
emmm I run again and I can get the correct result. maybe you are doing something wrong... can you post your environment informaiton, like gpu, os, etc.

**Comment by zerollzeng** [comment]
close due to inativity

**Comment by MolianWH** [comment]
Sorry for late. My computer was down and  rebuilt the envs for a long time. In the new envs, I got the keypoints correctly. Thanks!
