### ISSUE TITLE
about the confindence of object

### ISSUE THREAD

**Issue by guods** [zerollzeng/tensorrt-zoo#14]
I test YOLOV3 model with TensorRT7.0 (float16), I found that the confindence of all detetected objects is greater than 0.5（no confidence filtering）; do you know the reason?

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tensorrt-zoo/blob/dd6381f82cf35cac2c2cb4feb935a0b447e0c128/yolov3/YoloV3.cpp#L141

and

https://github.com/zerollzeng/tensorrt-zoo/blob/dd6381f82cf35cac2c2cb4feb935a0b447e0c128/yolov3/YoloV3.cpp#L88-L94

maybe take a look at this? I forgot the details of nms ：）

**Comment by guods** [comment]
I know do nms; but before  nms , the confindence of all detetected objects has been  greater than 0.5.

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tiny-tensorrt/blob/69e64d10270b518c1356b50d9dff1553e3d8c1ce/plugin/YoloLayerPlugin/YoloLayerPlugin.hpp#L22

and

https://github.com/zerollzeng/tiny-tensorrt/blob/69e64d10270b518c1356b50d9dff1553e3d8c1ce/plugin/YoloLayerPlugin/YoloLayerPlugin.cu#L283-L300

Just change value of IGNORE_THRESH if you need, note that their are gpu and cpu forward of yolo layer plugin

**Comment by guods** [comment]
Thanks for your reply, I has been solved it.
