### ISSUE TITLE
关于608的yolo3

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [zerollzeng/tensorrt-zoo#16]
我改了class YoloV3 的
```
int mNetWidth = 608;
int mNetHeight = 608;
```
改了caffe的prototxt
```
input: "data"
input_dim: 1
input_dim: 3
input_dim: 608
input_dim: 608
layer {
    bottom: "layer82-conv"
    bottom: "layer94-conv"
    bottom: "layer106-conv"
    top: "yolo-det"
    name: "yolo-det"
    type: "Yolo"
}
```
请问还需要改什么嘛 我改完之后一直各种报错 但是改回去用416就没错，有时候报错在Trt::CopyFromDeviceToHost，有时候又报错在cv::Mat::release...就很奇怪 但是Trt::CopyFromDeviceToHost没报错的情况下是有结果的。，但是Trt::CopyFromDeviceToHost不报错cv::Mat::release就会报错。。。好奇怪

**Comment by ZHEQIUSHUI** [comment]
还有就是batchsize，没有看到yolo有batchsize的操作，openpose倒是有Array有个维度可以操作，但是yolo就直接memcpy出来一串float。。。咋整啊这

**Comment by zerollzeng** [comment]
sry I can't help you with this, you may need to dig into source code by yourself

**Comment by zerollzeng** [comment]
take a quick look, maybe you just modify Yolov3.h and Yolov3.cpp? always debug from top to bottom

**Comment by ZHEQIUSHUI** [comment]
请问当我使用batchsize=2 然后输入两张图片的时候 我怎么知道“mpDetCpu”里面的数据谁是谁的啊

**Comment by zerollzeng** [comment]
for example output size is 100 for 1 image, if you use batchsize=2 them the output size should be 200, 
mpdetcpu[0-99] is for image 1 and mpdetcpu[100-199] is the output of image 2.

**Comment by ZHEQIUSHUI** [comment]
> for example output size is 100 for 1 image, if you use batchsize=2 them the output size should be 200,
> mpdetcpu[0-99] is for image 1 and mpdetcpu[100-199] is the output of image 2.

i have fixed this bug and pull requests,plz check it out and merge

**Comment by guods** [comment]
@zerollzeng  @ZHEQIUSHUI did you solve the question? I use batchsize=2, output size * batchsize, there were only the results of first images, else vaules in mpdetcpu is 0.

**Comment by guods** [comment]
@zerollzeng @ZHEQIUSHUI I see pull requests, I solved my question, thanks.

**Comment by zerollzeng** [comment]
@ZHEQIUSHUI Can  you upload your test code ASAP? :smiley::smiley::smiley:

**Comment by ZHEQIUSHUI** [comment]
i have commit and pull request,please check it out and merge

**Comment by zerollzeng** [comment]
Already merge and update, thanks for your contribution to this project again @ZHEQIUSHUI, it will help others a lot :+1:
