### ISSUE TITLE
The model has only class, no results.

### ISSUE THREAD

**Issue by guods** [zerollzeng/tensorrt-zoo#18]
windows10 ,GTX TITan X TensorRT7 cuda10 cudnn 7.6.5
The model has only class. Before transfering the tensorrt engine, the results of the model is correct; I created the engine and test, there were no results. Can you help me ?

**Comment by zerollzeng** [comment]
you mean when you load the model from engine file , you cannot get any output result?

**Comment by zerollzeng** [comment]
close due to inativity
