### ISSUE TITLE
getPluginCreator could not find plugin PReLU_TRT version 1

### ISSUE THREAD

**Issue by MolianWH** [zerollzeng/tensorrt-zoo#19]
Hi, Thanks for your greate contribution that helps me a lot. I meet some errors seems that you have met similar before. 
***
**Describe the bug**
I try to use the openpose.engine generate from tensorrt-zoo in NVIDIA DeepStream. I set the configuration file correctly. But it report errors could not find plugin PReLU_TRT. Bellow is the errors  screenshot.

**Screenshots**
![Screenshot from 2020-04-29 15-29-46](https://user-images.githubusercontent.com/33748947/80570976-5f497600-8a2e-11ea-9689-b44d78c6b31c.png)

**System environment :**
 - OS: Ubuntu18.04
 - GPU: GeForce GTX 1070
 - NVIDIA Driver: 440.44
 - TensorRT version: 6.0.1.5
 - CUDA: 10.1
 - CUDNN: 7.6.4.38

---
I refer to the issue you had created https://github.com/NVIDIA/TensorRT/issues/263#issuecomment-563986438 . Have you solved the problems? Could you share your solutions? 
Thanks!

**Comment by zerollzeng** [comment]
sry I can't give useful advice about this
take a look at https://github.com/zerollzeng/tiny-tensorrt/tree/master/plugin/PReLUPlugin maybe helpful, it has very detailed comments. and perhaps modify some function will works :dancing_men:

**Comment by MolianWH** [comment]
Thanks. I'll have a look.

**Comment by zerollzeng** [comment]
close due to inativity
