### ISSUE TITLE
靓仔，trt 5.1.5的版本在哪啊

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [zerollzeng/tensorrt-zoo#2]
谢谢

**Comment by ZHEQIUSHUI** [comment]
这个仓和tiny-tensorrt都没看到有其他的branch啊
如果看到有空的话帮忙解决一下哦 谢谢

**Comment by zerollzeng** [comment]
你可以git log 看之前的信息, 我本来创建了5.1的分支, 但是后来没有继续维护5.x分支就删除掉了.
你如果要使用5.x分支的话可以
tensorrt-zoo: git reset --hard 0c817fef 
tiny-tensorrt: git reset --hard 0b4f01b1 
但是我还是建议你使用最新的版本哦, 新的优化和bug修复都只在最新的提交上做了.

**Comment by ZHEQIUSHUI** [comment]
啊啊啊啊，我本来是要在xaiver上跑的，上面只有5.1.6,妹想到突然更新了6.0！！！6.0应该可以兼容你的项目叭！！！

**Comment by zerollzeng** [comment]
emmm 我不是很熟悉xavier, 不过我去查了一下应该是可以支持的. 见https://developer.nvidia.com/jetpack-4_3_DP

**Comment by ZHEQIUSHUI** [comment]
谢谢你！！！！

**Comment by zerollzeng** [comment]
不客气,有问题再提issue

**Comment by deep-practice** [comment]
6.0版本的代码在trt 5.1.5上面完全没法运行吗？

**Comment by zerollzeng** [comment]
> 6.0版本的代码在trt 5.1.5上面完全没法运行吗？

这个我也没有试过,有可能会无法运行. 你可以尝试运行一下,可能会有一些api不兼容报错,自己修改一下就好了
