### ISSUE TITLE
YoloV3 OpenPose run errors

### ISSUE THREAD

**Issue by xiangdeyizhang** [zerollzeng/tensorrt-zoo#22]
首先YlovV3运行，没有检测结果，我用的是Xavier NX。但是Openpose运行过不去，报错的结果是=====> malloc extra memory done
CUDA error 209 at /home/xz/Documents/tensorrt-zoo/tiny-tensorrt/plugin/PReLUPlugin/PReLUPlugin.cu:183

**Comment by zerollzeng** [comment]
can you post more information? your environment and log output.
btw
https://github.com/zerollzeng/tiny-tensorrt/issues/22#issuecomment-635741579 might be helpful

**Comment by xiangdeyizhang** [comment]
我使用的TensorRT是7.0的版本，cuda10.0以上版本。这个TensorRT版本有影响吗

**Comment by zerollzeng** [comment]
emmm TensorRT 7 should not be a problem, since you are using Xavier NX, which is a volta architecture device, can you post your running output? and cuda error 209 should be the keypoint, try google it :-D
