### ISSUE TITLE
cmake -D PYTHON_API=ON ..出现问题

### ISSUE THREAD

**Issue by xuluxulu** [zerollzeng/tensorrt-zoo#23]
-- LTO enabled
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDART
    linked by target "testyolov3" in directory /home/ts006/TS_xl/tensorrt-zoo/yolov3
    linked by target "testopenpose" in directory /home/ts006/TS_xl/tensorrt-zoo/openpose

-- Configuring incomplete, errors occurred!
See also "/home/ts006/TS_xl/tensorrt-zoo/build/CMakeFiles/CMakeOutput.log".
See also "/home/ts006/TS_xl/tensorrt-zoo/build/CMakeFiles/CMakeError.log".

**Comment by zerollzeng** [comment]
can you post your environmental informaiton? looks like you didn't install cuda correctly.

**Comment by xuluxulu** [comment]
ubuntu环境
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  6%   47C    P8    13W / 250W |    430MiB / 11175MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1310      G   /usr/lib/xorg/Xorg                            16MiB |
|    0      1344      G   /usr/bin/gnome-shell                          66MiB |
|    0     21019      G   /usr/lib/xorg/Xorg                           147MiB |
|    0     21123      G   /usr/bin/gnome-shell                         100MiB |
|    0     21604      G   /opt/teamviewer/tv_bin/TeamViewer             15MiB |
|    0     22756      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files    81MiB |
+-----------------------------------------------------------------------------+

**Comment by xuluxulu** [comment]
cuda已安装，并可以正常使用

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tensorrt-zoo/blob/aad31b9680484ee61007daa6037126321b0cb7eb/CMakeLists.txt#L21

please check this path and see if it's correct for your system

**Comment by xuluxulu** [comment]
我的／ｕｓｒ／ｌｏｃａｌ／ｃｕｄａ下没有targets目录，难道是这个问题吗吗

**Comment by zerollzeng** [comment]
try replace this path with /usr/local/cuda/lib64 where libcudart.so is located

**Comment by zerollzeng** [comment]
or other path, if you still can not find this so, them perhaps you need to reinstall cuda :-)

**Comment by xuluxulu** [comment]
我的在usr/local/cuda10.0/lib64 /目录下有这个文件 libcudart.so

**Comment by xuluxulu** [comment]
可以把  find_library(CUDART cudart HINTS /usr/local/cuda/targets/x86_64-linux/lib/) 
修改成 find_library(CUDART cudart HINTS /usr/local/cuda10.0/lib64/) 吗

**Comment by xuluxulu** [comment]
我把上述更改后，可以cmake了，但在make出现问题，
/home/ts006/TS_xl/tensorrt-zoo/yolov3/YoloV3.cpp:131:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (size_t i = 0; i < batchsize; i++)
                     ~~^~~~~~~~~~~
yolov3/CMakeFiles/testyolov3.dir/build.make:65: recipe for target 'yolov3/CMakeFiles/testyolov3.dir/YoloV3.cpp.o' failed
make[2]: *** [yolov3/CMakeFiles/testyolov3.dir/YoloV3.cpp.o] Error 1
CMakeFiles/Makefile2:214: recipe for target 'yolov3/CMakeFiles/testyolov3.dir/all' failed
make[1]: *** [yolov3/CMakeFiles/testyolov3.dir/all] Error 2
Makefile:86: recipe for t

**Comment by zerollzeng** [comment]
that's weird, could you post the complete output of cmake and make?

**Comment by zerollzeng** [comment]
by the way you can wrap the output in a code section, which improve the readability.

**Comment by zhanghongyong123456** [comment]
> https://github.com/zerollzeng/tensorrt-zoo/blob/aad31b9680484ee61007daa6037126321b0cb7eb/CMakeLists.txt#L21
> 
> please check this path and see if it's correct for your system
If is Win10 system, this path should point to where
