### ISSUE TITLE
result is empty when run_model=2(openpose)

### ISSUE THREAD

**Issue by lwcode** [zerollzeng/tensorrt-zoo#24]
when I test testopenpose and set the run_model=2, the result is empty. run_model=0 work well, how to fix it?

**Comment by zerollzeng** [comment]
you are using int8 mode so before you run the model you have do the calibration.

**Comment by lwcode** [comment]
> you are using int8 mode so before you run the model you have do the calibration.

Thanks for your reply, I will try to do the calibration. Do you have any experience for it?

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tensorrt-zoo/blob/aad31b9680484ee61007daa6037126321b0cb7eb/openpose/testopenpose.cpp#L86

take a look at here, prepare about 1000 images serialize it to 3*480*640 vector then put it into calibratorData, then TensorRT will do the calibration automatically.

**Comment by lwcode** [comment]
It still output empty results, my code is: 
```
cv::VideoCapture capture(args.img_calib);
cv::Mat img;
long totalFrameNumber = int(capture.get(cv::CAP_PROP_FRAME_COUNT)/args.batchsize);
calibratorData.resize(totalFrameNumber);
std::cout << "start to read calibrate images..." << std::endl;
for (size_t i = 0; i < calibratorData.size(); i++) 
{
	for (size_t k = 0; k < args.batchsize; k++)
	{
		capture.read(img);
		if (img.empty())
			break;
		cv::cvtColor(img, img, cv::COLOR_BGR2RGB);

		cv::resize(img, img, cv::Size(args.width, args.height));
		calibratorData[i].resize(args.batchsize * 3 * args.height * args.width);
		
		unsigned char* data = img.data;
		for (int c = 0; c < 3; c++) {
			for (int j = 0; j < args.width*args.height; j++) {
				calibratorData[i][j + c * args.width*args.height + k * 3 * args.height*args.width] = (float)data[j * 3 + c];
			}
		}
	}
}
```
