### ISSUE TITLE
编译成功，运行成功，但是没有检测输出

### ISSUE THREAD

**Issue by tecsai** [zerollzeng/tensorrt-zoo#29]
作者你好，我下载了你的tensorrt-zoom， 在NX上编译成功，也能运行，但是最终检测结果没有信息。

**Comment by zerollzeng** [comment]
能贴一下cmake和运行的log output吗?

**Comment by tecsai** [comment]
作者你好，很兴奋你竟然回复了。
现在是这么一个情况，我把forwardGpu改用forwardCpu之后，就输出了，我还在看为什么用forwardGpu没有输出，我觉得问题应该不大了。
现在有另外一个问题，你在构造YoloV3时，有一个factor参数，针对416的输入是63883，针对608的输入是136459，我不太明白取值的依据，能否指点一下。

**Comment by zerollzeng** [comment]
> 作者你好，很兴奋你竟然回复了。

周末躺尸时间神圣不可侵犯

> 现在有另外一个问题，你在构造YoloV3时，有一个factor参数，针对416的输入是63883，针对608的输入是136459，我不太明白取值的依据，能否指点一下。

这个请查看issue #5 



> 现在是这么一个情况，我把forwardGpu改用forwardCpu之后，就输出了，我还在看为什么用forwardGpu没有输出，我觉得问题应该不大了。

解决之后可以评论留一下解决办法嘛,对其他人可能有用, Thanks for your feedback and contribution

**Comment by zerollzeng** [comment]
Closed
