### ISSUE TITLE
靓仔我又来了

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [zerollzeng/tensorrt-zoo#3]
我在xavier上试了 yolo是可以的 但是openpose没有结果，所以我又在我的电脑上试了，openpose还是没结果,但是yolo也是一样可以的。难道我用错模型了...

>/testopenpose --prototxt ~/lib/openpose/openpose/models/pose/body_25/pose_deploy.prototxt --caffemodel ~/lib/openpose/openpose/models/pose/body_25/pose_iter_584000.caffemodel --save_engine body_25_fp16.engine --run_mode 1 --input ../test.jpg 

>/testopenpose --prototxt ~/lib/openpose/openpose/models/pose/body_25/pose_deploy.prototxt --caffemodel ~/lib/openpose/openpose/models/pose/body_25/pose_iter_584000.caffemodel --save_engine body_25_fp32.engine --run_mode 0 --input ../test.jpg 

fp16和fp32这两个我都试过了。

我的电脑是2070 cuda10.0

还有一个很尴尬的请求，就是我想在我的qt项目用openpose，但是呢，我不是很懂cu文件在qt怎么编译（其实是完全不懂cuda编程），所以希望如果有空的话能不能把openpose弄成so这样.....当然如果没空就算了叭，我还学得动

**Comment by ZHEQIUSHUI** [comment]
西大普泵，我用qt编译成功了....但是还是没结果唉

**Comment by zerollzeng** [comment]
只要改动一下CMakeLists.txt就可以编译成动态库,我是为了方便测试才编译成可执行文件的.另外关于没有结果这个问题, 你有更多的信息吗?

**Comment by zerollzeng** [comment]
我自己在本地测试fp16和fp32都是可以产生正确结果的.大概长这样
![result](https://user-images.githubusercontent.com/38289304/71391453-137d5f00-263f-11ea-9bc3-2c4326575b37.jpg)

**Comment by ZHEQIUSHUI** [comment]
我用的是tensorrt6.0.1.5 本来是用了cudnn7.5 警告了 说用7.6.3  就下载了7.6.3，但是还是不行
我在openpose的cu里面把你注释的输出全部弄开了 
[2019-12-24 11:21:22.964] [info] net forward takes 5.08333 ms
> for (int i =0;i< 10;i++) {
         std::cout << net_output[i] << " ";
     }

对应的就是

>0.000327133 0.000534454 7.04681e-05 0.000125931 0.000263619 0.000313534 0.000187123 0.000285778 0.000753581 0.0006608 

>for(int i=0;i<60*80;i++) {
         std::cout << int(net_output[i]*255/25);
         if((i+1)%80 == 0) {
             std::cout << std::endl;
         }
     }

对应

>00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000001010101000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
number of person: 0

**Comment by ZHEQIUSHUI** [comment]
我把doInfence里的注释解开了，下面是输出。然后现在用的trt是6.0.1.5 cudnn7.6.3

[2019-12-24 11:28:55.425] [info] create plugin factory
[2019-12-24 11:28:55.425] [info] yolo3 params: class: 1, netSize: 416 
[2019-12-24 11:28:55.425] [info] upsample params: scale: 2
[2019-12-24 11:28:55.426] [info] prototxt: /home/arno/lib/openpose/openpose/models/pose/body_25/pose_deploy.prototxt
[2019-12-24 11:28:55.426] [info] caffeModel: /home/arno/lib/openpose/openpose/models/pose/body_25/pose_iter_584000.caffemodel
[2019-12-24 11:28:55.426] [info] engineFile: /home/arno/baidunetdiskdownload/tensorrt-zoo/bin/body_25_fp16.engine
[2019-12-24 11:28:55.426] [info] outputBlobName: 
net_output 
[2019-12-24 11:28:55.426] [info] deserialize engine from /home/arno/baidunetdiskdownload/tensorrt-zoo/bin/body_25_fp16.engine
[2019-12-24 11:28:57.362] [info] max batch size of deserialized engine: 1
[2019-12-24 11:28:57.363] [info] create execute context and malloc device memory...
[2019-12-24 11:28:57.363] [info] init engine...
[2019-12-24 11:28:57.364] [info] malloc device memory
nbBingdings: 2
[2019-12-24 11:28:57.364] [info] input: 
[2019-12-24 11:28:57.364] [info] binding bindIndex: 0, name: image, size in byte: 3072
[2019-12-24 11:28:57.364] [info] binding dims with 3 dimemsion
3 x 16 x 16   
[2019-12-24 11:28:57.364] [info] output: 
[2019-12-24 11:28:57.364] [info] binding bindIndex: 1, name: net_output, size in byte: 1248
[2019-12-24 11:28:57.364] [info] binding dims with 3 dimemsion
78 x 2 x 2   
=====>malloc extra memory for openpose...
heatmap Dims3
heatmap size: 1 78 2 2
allocate heatmap host and divice memory done
resize map size: 1 78 8 8
kernel size: 1 78 8 8
allocate kernel host and device memory done
peaks size: 1 25 128 3
allocate peaks host and device memory done
=====> malloc extra memory done
[2019-12-24 11:28:57.369] [info] net forward takes 4.93421 ms

>for (int i =0;i< 10;i++) {
         std::cout << net_output[i] << " ";
     }

对应

>0.000358858 0.000556114 8.63859e-05 0.000114613 0.00025778 0.000307868 0.000192473 0.000267894 0.00071007 0.00062031 

>std::cout << std::endl;
     for(int i=0;i<60*80;i++) {
         std::cout << int(net_output[i]*255/25);
         if((i+1)%80 == 0) {
             std::cout << std::endl;
         }
     }

对应

>00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000001010101000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
number of person: 0

**Comment by ZHEQIUSHUI** [comment]
看起来可能有点累眼睛哈....然后我的图片就是
![result](https://user-images.githubusercontent.com/46700201/71392001-72dc6e80-2641-11ea-8b14-6c134a649285.jpg)

**Comment by zerollzeng** [comment]
你要修改prototxt里面的
```
name: "OpenPose - BODY_25"
input: "image"
input_dim: 1 # This value will be defined at runtime
input_dim: 3
input_dim: 480 # This value will be defined at runtime
input_dim: 640 # This value will be defined at runtime
```
input dim 为480和640,然后删除掉生成的引擎文件,应该可以出来正确的结果.

详细可以参考[readme](https://github.com/zerollzeng/tensorrt-zoo/blob/master/docs/openpose.md)

**Comment by ZHEQIUSHUI** [comment]
啊 对不起 我的错 我记得我看了这个的 但是没太在意..太谢谢你啦

**Comment by ZHEQIUSHUI** [comment]
我 close啦 再次谢谢你！
