### ISSUE TITLE
你好，请问哪里有aarch64_linux 的cudnn7.6.5 和tensorrt6 下载吗？或者源码。我使用的jetsonnano，nvdia上没有aarch64_linux 的cudnn7.6.5 和tensorrt6 下载

### ISSUE THREAD

**Issue by liuwei0812** [zerollzeng/tensorrt-zoo#30]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**

**To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System environment (please complete the following information):**
 - OS: 
 - TensorRT version: 
 - Others:

**Additional context**

**Comment by zerollzeng** [comment]
Perhaps you should take a look at https://developer.nvidia.com/embedded/jetpack

**Comment by liuwei0812** [comment]
thanks, jetpack4.3 solved the tensorrt question ;
and I followed the general instructions + Jetson Nano suggestions from #25 and the testImg resulting right, but some img works not right(i use windows openpose and coco_18 works right), I think my download body25 model not very good ,can you give me a body25 dowmload address? thanks.
 I followed the general instructions + Jetson Nano suggestions from #25  and jetson Nano works gpu 99%  and doInference a img use 1.5s  use time is so long(640*480), I see in openpose.md use time 89ms,   jetson nano sm-53 works so slow，can you  give me some suggestion to make jetson nano work faster?

**Comment by zerollzeng** [comment]
> can you give me a body25 dowmload address? thanks.

I used the official openpose body25 model, just download it from openpose repo.



> I followed the general instructions + Jetson Nano suggestions from #25 and jetson Nano works gpu 99% and doInference a img use 1.5s use time is so long(640*480), I see in openpose.md use time 89ms, jetson nano sm-53 works so slow，can you give me some suggestion to make jetson nano work faster?

jetson nano's inference speed is not as fast as desktop gpus, so I think it's normal it takes longer time, for you need , I think you should consider some lignt-weighted pose estimation models so that it can meed your requirement in embedded platfrom instead of heavy model like openpose.

**Comment by liuwei0812** [comment]
ok,thanks!
I download  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel  It's official ?

**Comment by zerollzeng** [comment]
Closed.
