### ISSUE TITLE
为啥不用tensorrt而是tiny tensorrt呢？

### ISSUE THREAD

**Issue by opentld** [zerollzeng/tensorrt-zoo#32]
没啥原因，就是喜欢原汁原味。。。毕竟tiny的更新赶不上原版吧。。。
有兴趣移植一下嘛？

@zerollzeng

**Comment by zerollzeng** [comment]
> 没啥原因，就是喜欢原汁原味。。。毕竟tiny的更新赶不上原版吧。。

tiny-tensorrt也只是加个壳，用起来更方便一点而已



> 有兴趣移植一下嘛？

现在没有时间做，事实上本来这个仓库也要跟着tiny-tensorrt一起更新的，可以有更好的支持，但是我没有时间做,sry
