### ISSUE TITLE
add post-proc How to add post-processing to make the line drawn on the human body image instead of just the keypoints

### ISSUE THREAD

**Issue by weilanShi** [zerollzeng/tensorrt-zoo#36]
Thank you very much for your contribution. I have another question: when testing testopopose, i can only get keypoints. And I can see that there is post-processing part in the code. How to add post-processing part to the testopopose.cpp to make the line drawn on the human body image instead of just the keypoints. Thank you very much ! (The third picture is what I want to get)

**Comment by zerollzeng** [comment]
Take a loot at
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
Which describe how the keypoint index and how to conect them as you need

**Comment by zerollzeng** [comment]
Noted that the model used in tensorrt-zoo is body-25

**Comment by weilanShi** [comment]
> Take a loot at
> https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
> Which describe how the keypoint index and how to conect them as you need
Thank you for your reply, it's work
