### ISSUE TITLE
  changing this project to coco_ 18 key points predicted

### ISSUE THREAD

**Issue by weilanShi** [zerollzeng/tensorrt-zoo#37]
Who changed this project to coco_18 keypoints predicted and work successful? i changed the  mNumPeaks (openpose.hpp) to 18, and  the net_output.resize(78  60  80) to net_output.resize(57  60  80) （openpose.cu） and the op::PoseModel::BODY_25 to op::PoseModel::COCO_18 (op::connectBodyPartsCpu of openpose.cu ) and changed the const auto& bodyPartPairs and  const auto numberBodyParts (void connectBodyPartsCpu of BodyPartConnector.cu). Unfortunately, there is none in the result.jpg. Anyone could help me, thanks!

**Comment by zerollzeng** [comment]
All the post-processing was ported from https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/src/openpose/net which might be helpful to you

**Comment by zerollzeng** [comment]
Closed due to inativity
