### ISSUE TITLE
Yolov3加速的一些疑问

### ISSUE THREAD

**Issue by guods** [zerollzeng/tensorrt-zoo#4]
YoloV3加速代码和https://github.com/lewes6369/TensorRT-Yolov3的实现，但是你的前向速度要比它快很多，你知道最大的差异点在哪吗？

**Comment by zerollzeng** [comment]
应该是版本问题吧, lewes6369的是基于tensorrt 5.0的,我的tiny-tensorrt目前支持最新的7.0
