### ISSUE TITLE
calibratorData怎么来的

### ISSUE THREAD

**Issue by 121786404** [zerollzeng/tensorrt-zoo#7]
这个应该是用一些图片自动标定出来的吧？能把这部分功能集成到demo里面吗？

**Comment by zerollzeng** [comment]
这个部分考虑过集成,但是不好做,因为每个模型的校准数据不一样. calibratorData就是普通的模型输入.比如你可以准备500张测试的图片, 经过你的预处理后的数据就是校准的数据.直接传进去即可完成校准.说简单点就是利用真实的输入数据对int8量化后的模型进行微调

**Comment by 121786404** [comment]
我修改了 yolo3test.cpp ，仿照openpose，添加了calibratorData，不过出来的框是错的

**Comment by 121786404** [comment]
yolo比较简单，大家学习比较方便，给yolo加一个int8标定吧，这样才是完整的INT8

**Comment by zerollzeng** [comment]
如果你是模仿这里的代码
https://github.com/zerollzeng/tensorrt-zoo/blob/bde2893662d47db29c37fd247834c2a49f1e281b/openpose/testopenpose.cpp#L86
那么出来的结果肯定是错的,因为需要将真实的输入图片作为校准的数据,我这里是为了验证int8量化可以用.所以自己构造了input.

**Comment by zerollzeng** [comment]
如果有时间的话我会写一个tiny-tensorrt关于int8的sample,但是这个的优先级比较低
