### ISSUE TITLE
when GPU Framwork version number is less than 61, compile error

### ISSUE THREAD

**Issue by guods** [zerollzeng/tensorrt-zoo#8]
1.  complie error 
more than one conversion function from "const __half" to a built-in type applies; on line 44 PReLUPlugin.cu 
2.
 - OS: windows10, cuda10.0, cudnn7.5.0
 - TensorRT version: TensorRT5.1.5.0

**Comment by guods** [comment]
get the same error with TnesorRT 7.0.1.1

**Comment by zerollzeng** [comment]
that's because when graphic card's sm version less than 6.0, they don't support fp16, and my custom plugin has a fp16 implementation, which graphic card you are using now?

**Comment by zerollzeng** [comment]
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
you may take a look at this article

**Comment by guods** [comment]
GTX TiTan X(52), but I run the demo https://github.com/lewes6369/TensorRT-Yolov3 on windows10 with TensorRT5.1.5.0 , cuda10.0 and cudnn7.5.0, the result is normal.

**Comment by guods** [comment]
Thanks for your reply, the problem has been solved on TiTan X.

**Comment by zerollzeng** [comment]
that's becuase I disable sm version less than 6.0. if you want to make it run, you can go to
https://github.com/zerollzeng/tiny-tensorrt/blob/69e64d10270b518c1356b50d9dff1553e3d8c1ce/cmake/CUDA_utils.cmake#L17
then comment some lines related to fp16 like
https://github.com/zerollzeng/tiny-tensorrt/blob/69e64d10270b518c1356b50d9dff1553e3d8c1ce/plugin/PReLUPlugin/PReLUPlugin.cu#L184
I think that would solve your problem
